version: "3"

services:

  postgres:
    image: postgres
    container_name: postgres
    user: postgres
    environment:
      POSTGRES_DB: vfsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - ./dll/dll.sql:/docker-entrypoint-initdb.d/dll.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-h", "localhost", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  polish_api:
    image: polish_api
    container_name: polish_api
    # restart: "on-failure"
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy
