version: "3"

services:

  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
      http.port: 9200
    ports:
    - 9200:9200
    - 9300:9300
    healthcheck:
      test: curl -u elastic:elastic -s -f elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres
    container_name: postgres
    user: postgres
    environment:
      POSTGRES_DB: vfsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - ./dll/dll.sql:/docker-entrypoint-initdb.d/dll.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-h", "localhost", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  polish_api:
    image: polish_api
    container_name: polish_api
    # restart: "on-failure"
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy