----------------EXERCISE 1. SIMPLE SQL QUERIES----------------

SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;
SELECT * FROM PROJECT;
SELECT * FROM EMP_ACT;

--1.1
SELECT EMPNO, LASTNAME, BIRTHDATE, SALARY
FROM EMPLOYEE 
WHERE SALARY > 30000;

--1.2
SELECT LASTNAME, FIRSTNME, WORKDEPT
FROM EMPLOYEE 
ORDER BY WORKDEPT, LASTNAME DESC;

--1.3
SELECT DISTINCT EDLEVEL
FROM EMPLOYEE
ORDER BY EDLEVEL DESC;

--1.4
SELECT DISTINCT EMPNO, PROJNO
FROM EMP_ACT
WHERE EMPNO >= 100
ORDER BY EMPNO;

--1.5
SELECT LASTNAME, SALARY, BONUS FROM EMPLOYEE
WHERE SEX = 'M';


--1.6
SELECT LASTNAME, SALARY, COMM FROM EMPLOYEE
WHERE SALARY > 20000
AND HIREDATE > '1979-01-01';

--1.7
SELECT LASTNAME, SALARY, BONUS, COMM FROM EMPLOYEE
WHERE (SALARY > 22000 
        AND BONUS = 400
)
OR (BONUS = 500
        AND COMM < 1900
)
ORDER BY LASTNAME;

--1.8
SELECT LASTNAME, SALARY, BONUS, COMM FROM EMPLOYEE
WHERE (SALARY > 22000 
        AND (BONUS = 400
        OR BONUS = 500)
        AND COMM < 1900)
ORDER BY LASTNAME;

--1.9
SELECT PROJNO, ACTNO, EMSTDATE, EMENDATE
FROM EMP_ACT
WHERE PROJNO LIKE 'AD%'
        AND ACTNO IN (10, 80, 180)
ORDER BY PROJNO, ACTNO;

--1.10
SELECT MGRNO, DEPTNO
FROM DEPARTMENT
WHERE MGRNO IS NOT NULL
ORDER BY MGRNO;

--1.11
SELECT LASTNAME, SALARY, BONUS
FROM EMPLOYEE
WHERE BONUS BETWEEN 800 AND 1000
ORDER BY BONUS, EMPNO;

--1.12
SELECT LASTNAME, SALARY, BONUS 
FROM EMPLOYEE
WHERE WORKDEPT BETWEEN 'A00' AND 'C01'
ORDER BY LASTNAME, EMPNO;


--1.13
SELECT PROJNO, PROJNAME
FROM PROJECT
WHERE PROJNAME LIKE '%SUPPORT%'
ORDER BY PROJNO;

--1.14
SELECT DEPTNO, DEPTNAME
FROM DEPARTMENT
WHERE DEPTNO LIKE '_1_'
ORDER BY DEPTNO;

--1.15
SELECT LASTNAME, FIRSTNME, MIDINIT, SALARY
FROM EMPLOYEE
WHERE JOB NOT IN ('MANAGER', 'PRES')
ORDER BY SALARY DESC LIMIT 5;

----------------EXERCISE 2. RETRIEVING DATA FROM MULTIPLE TABLES----------------
--2.1
SELECT LASTNAME, FIRSTNME, DEPTNAME
FROM EMPLOYEE
        JOIN DEPARTMENT
                ON WORKDEPT = DEPTNO
ORDER BY DEPTNAME, LASTNAME, FIRSTNME;

--2.2
SELECT LASTNAME, FIRSTNME, DEPTNAME, JOB
FROM EMPLOYEE
        JOIN DEPARTMENT
                ON WORKDEPT = DEPTNO
WHERE WORKDEPT BETWEEN 'A02' AND 'D22'
        AND JOB != 'MANAGER' 
ORDER BY DEPTNAME, LASTNAME, FIRSTNME;

--2.3
SELECT DEPTNAME, LASTNAME, FIRSTNME
FROM EMPLOYEE
        JOIN DEPARTMENT
                ON EMPNO = MGRNO
ORDER BY DEPTNAME;

--2.4
SELECT DEPTNAME, LASTNAME, FIRSTNME
FROM EMPLOYEE
        JOIN DEPARTMENT
                ON WORKDEPT = DEPTNO
WHERE JOB = 'MANAGER'
ORDER BY DEPTNAME;

--2.5
SELECT  PROJECT.PROJNO, PROJNAME, ACTNO
FROM PROJECT
        JOIN EMP_ACT
                ON PROJECT.PROJNO = EMP_ACT.PROJNO
WHERE PROJECT.PROJNO LIKE 'AD%'
ORDER BY PROJECT.PROJNO, ACTNO;

--2.6
SELECT EMPNO, LASTNAME, PROJNO
FROM EMPLOYEE 
        JOIN PROJECT
                ON  WORKDEPT = DEPTNO 
WHERE PROJNO = 'AD3113'
ORDER BY EMPNO, PROJNO;

--2.7
SELECT EMPNO, PROJECT.PROJNO, PROJNAME, ACTNO, EMSTDATE
FROM EMP_ACT 
        JOIN PROJECT
                ON  PROJECT.PROJNO = EMP_ACT.PROJNO
WHERE EMSTDATE = '1982-10-01' -- there is no such
ORDER BY PROJECT.PROJNO, EMPNO, ACTNO;

SELECT EMPNO, PROJECT.PROJNO, PROJNAME, ACTNO, EMSTDATE
FROM EMP_ACT 
        JOIN PROJECT
                ON  PROJECT.PROJNO = EMP_ACT.PROJNO
WHERE EMSTDATE = '2002-10-01' -- for example
ORDER BY PROJECT.PROJNO, EMPNO, ACTNO;

--2.8
SELECT WORKDEPT, LASTNAME, PROJNAME, ACTNO
FROM EMPLOYEE
        JOIN EMP_ACT
                ON EMPLOYEE.EMPNO = EMP_ACT.EMPNO
        JOIN PROJECT 
                ON EMP_ACT.PROJNO = PROJECT.PROJNO
WHERE WORKDEPT = 'A00'
ORDER BY PROJNAME, ACTNO;

--2.9
SELECT DISTINCT WORKDEPT, LASTNAME, PROJNAME, ACTNO
FROM EMP_ACT
        JOIN EMPLOYEE
                ON EMP_ACT.EMPNO = EMPLOYEE.EMPNO
        JOIN PROJECT 
                ON EMP_ACT.PROJNO = PROJECT.PROJNO
WHERE WORKDEPT BETWEEN 'A00' AND 'C01'
ORDER BY WORKDEPT, LASTNAME, ACTNO;

--2.10
SELECT ACTNO, MGRNO, EMSTDATE, PROJNO, LASTNAME
FROM EMPLOYEE
        JOIN DEPARTMENT
                ON WORKDEPT = DEPTNO
        JOIN EMP_ACT
                ON EMPLOYEE.EMPNO = EMP_ACT.EMPNO
WHERE EMSTDATE >= '1982-10-15'
ORDER BY ACTNO, EMSTDATE;

--2.11
SELECT EMP.WORKDEPT AS DEPTNO, MGR.LASTNAME AS MANAGER, EMP.LASTNAME AS EMPLOYEE, MGR.HIREDATE AS M_HIREDATE, EMP.HIREDATE AS E_HIREDATE
FROM EMPLOYEE AS EMP
        JOIN EMPLOYEE AS MGR
                ON EMP.HIREDATE < MGR.HIREDATE
WHERE EMP.WORKDEPT = 'C01' -- there is no such IN A00 WORKDEPT
        AND MGR.WORKDEPT = 'C01'
        AND MGR.JOB = 'MANAGER'
ORDER BY EMP.LASTNAME;

----------------EXERCISE 3. SCALAR FUNCTIONS AND ARITHMETIC----------------
--3.1
SELECT LASTNAME, SALARY, (SALARY + SALARY * 0.05) AS INC_Y_SALARY, ((SALARY + SALARY * 0.05) / 12) AS INC_M_SALARY 
FROM EMPLOYEE
WHERE (SALARY + SALARY * 0.05) >= 20000
ORDER BY SALARY;

--3.2
SELECT LASTNAME, EDLEVEL, (SALARY + 1200) AS NEW_SALARY, ROUND((BONUS / 2),2) AS NEW_BONUS 
FROM EMPLOYEE
WHERE EDLEVEL = 18 
        OR EDLEVEL = 20
ORDER BY EDLEVEL DESC, NEW_SALARY;

--3.3
SELECT WORKDEPT, LASTNAME, SALARY, (SALARY - 1000) AS DESCR_SALARY 
FROM EMPLOYEE
WHERE WORKDEPT = 'D11' 
        AND (SALARY BETWEEN (20000 * 0.8)
                AND  (20000 * 1.2)
        )
ORDER BY SALARY;

--3.4
SELECT WORKDEPT, LASTNAME, (SALARY + COMM + BONUS) AS INCOME
FROM EMPLOYEE
WHERE WORKDEPT = 'D11'
        AND (SALARY + COMM + BONUS) > SALARY * 0.1
        AND SALARY IS NOT NULL
        AND COMM IS NOT NULL
        AND BONUS IS NOT NULL
ORDER BY INCOME DESC;

--3.5
SELECT DEPTNO, DEPTNAME, COALESCE (MGRNO, 'UNKNOWN') AS MGRNO
FROM DEPARTMENT
WHERE MGRNO IS NULL;

--3.6
SELECT PROJNO, COALESCE (MAJPROJ, 'MAIN PROJECT') AS MAJOR_PROJECT
FROM PROJECT
WHERE PROJNO LIKE 'MA%'
ORDER BY PROJNO;

--3.7
SELECT EMPNO, LASTNAME, YEAR(HIREDATE - BIRTHDATE) AS AGE
FROM EMPLOYEE
WHERE YEAR(HIREDATE - BIRTHDATE) < 25
ORDER BY AGE, EMPNO;

--3.8
SELECT YEAR(PRSTDATE) AS YEAR, MONTH(PRSTDATE) AS MONTH, PROJNO
FROM PROJECT
WHERE PRENDATE = '1982-12-01'
ORDER BY PROJNO;

--3.9
SELECT PROJNO, ROUND((DECIMAL(DAYS(PRENDATE) - DAYS(PRSTDATE)) / 7), 1) AS WEEKS
FROM PROJECT
WHERE PROJNO LIKE 'MA%'
ORDER BY PROJNO;

--3.10
SELECT PROJNO, PRENDATE AS ESTIMATED, (PRENDATE + ((DAYS(PRENDATE) - DAYS(PRSTDATE)) * 0.1) DAYS) AS EXPECTED
FROM PROJECT
WHERE PROJNO LIKE 'MA%'
ORDER BY PROJNO;

--3.11
SELECT (DAYS('2000-01-01') - DAYS('1969-07-20')) AS DAYS
FROM SYSIBM.SYSDUMMY1;

----------------EXERCISE 4. COLUMN FUNCTIONS AND GROUPING----------------
--4.1
SELECT WORKDEPT, SUM(SALARY) AS SUM_SALARY
FROM EMPLOYEE
GROUP BY WORKDEPT;

--4.2
SELECT WORKDEPT, COUNT(*) AS EMP_COUNT
FROM EMPLOYEE
GROUP BY WORKDEPT;

--4.3
SELECT WORKDEPT
FROM EMPLOYEE
GROUP BY WORKDEPT
HAVING COUNT(*) > 3;

--4.4
SELECT WORKDEPT, COUNT(*) AS DESIGNER
FROM EMPLOYEE
WHERE JOB = 'DESIGNER'
GROUP BY WORKDEPT;

--4.5


--4.6


----------------EXERCISE 5. UNION----------------
--5.1
SELECT LASTNAME, FIRSTNME, 'BEFORE A RAISE' AS WHEN, SALARY
FROM EMPLOYEE
WHERE JOB != 'MANAGER'
        AND WORKDEPT = 'D21'
UNION
SELECT LASTNAME, FIRSTNME, 'AFTER A RAISE' AS WHEN, SALARY + SALARY * 0.1
FROM EMPLOYEE
WHERE JOB != 'MANAGER'
        AND WORKDEPT = 'D21'
ORDER BY LASTNAME;


--5.2
SELECT WORKDEPT, EMPNO, SALARY
FROM EMPLOYEE
WHERE WORKDEPT = 'A00'
UNION
SELECT WORKDEPT, 'SUM' , SUM(SALARY)
FROM EMPLOYEE
WHERE WORKDEPT = 'A00'
GROUP BY WORKDEPT;

--5.3


--5.4


----------------EXERCISE 6. USING SUBQUERIES----------------
--6.1
SELECT WORKDEPT, EMPNO, LASTNAME, SALARY
FROM EMPLOYEE
WHERE SALARY >= (SELECT AVG(SALARY) + 5000
                 FROM EMPLOYEE
                )
ORDER BY WORKDEPT, EMPNO;

--6.2
SELECT EMPNO, LASTNAME 
FROM EMPLOYEE
WHERE EMPNO NOT IN (SELECT EMPNO
                FROM EMP_ACT
                );

--6.3
SELECT PROJNO, (DAYS(PRENDATE) - DAYS(PRSTDATE)) AS DAYS
FROM PROJECT
WHERE (DAYS(PRENDATE) - DAYS(PRSTDATE)) = (SELECT MIN((DAYS(PRENDATE) - DAYS(PRSTDATE)))
                                           FROM PROJECT);

--6.4


--6.5


----------------EXERCISE 7. MAINTAINING DATA----------------
--7.1
DROP TABLE TESTEMP IF EXISTS;
CREATE TABLE TESTEMP (
EMPNO CHAR(6) NOT NULL,
LASTNAME VARCHAR(15) NOT NULL,
WORKDEPT CHAR(3),
HIREDATE DATE,
SALARY DECIMAL(9,2),
BONUS DECIMAL(9,2)
);

--7.2
INSERT INTO TESTEMP
VALUES ('000111', 'SMITH', 'C01', '2000-06-06', 25000, 0),
('000222', 'BAKER', 'A00', '2000-06-06', 28000, NULL),
('000333', 'THOMAS', 'D11', '2000-06-06', 33000, 0);

--7.3
INSERT INTO TESTEMP
SELECT EMPNO, LASTNAME, WORKDEPT, HIREDATE, SALARY, BONUS 
FROM EMPLOYEE
WHERE EMPNO <= 50;

SELECT * FROM TESTEMP;
--7.4
UPDATE TESTEMP 
SET BONUS = 500
WHERE EMPNO = '000111';

--7.5
UPDATE TESTEMP 
SET SALARY = SALARY + 1000
WHERE WORKDEPT = 'C01';

--7.6


--7.7


--7.8


--7.9


--7.10

